In [2]:
import pyspark

In [3]:
from pyspark.sql import SparkSession

# Initialize SparkSession
spark = SparkSession.builder \
    .appName("Trial") \
    .config("spark.executor.memory", "1g") \
    .getOrCreate()

In [3]:
df1 = spark.read.parquet(
    "hdfs://namenode:9000/project-data/yellow_tripdata1.parquet"
)

df1.limit(5).toPandas()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1,1.60,1,N,229,237,1,10.0,3.5,0.5,3.00,0.0,1.0,18.00,2.5,0.0,0.0
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1,0.50,1,N,236,237,1,5.1,3.5,0.5,2.02,0.0,1.0,12.12,2.5,0.0,0.0
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1,0.60,1,N,141,141,1,5.1,3.5,0.5,2.00,0.0,1.0,12.10,2.5,0.0,0.0
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3,0.52,1,N,244,244,2,7.2,1.0,0.5,0.00,0.0,1.0,9.70,0.0,0.0,0.0
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3,0.66,1,N,244,116,2,5.8,1.0,0.5,0.00,0.0,1.0,8.30,0.0,0.0,0.0

In [4]:
df2 = spark.read.parquet(
    "hdfs://namenode:9000/project-data/yellow_tripdata2.parquet"
)

df2.limit(5).toPandas()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,2,2025-02-01 00:12:18,2025-02-01 00:32:33,3,3.12,1,N,246,79,1,19.8,1.00,0.5,5.11,0.0,1.0,30.66,2.5,0.0,0.75
1,2,2025-02-01 00:40:04,2025-02-01 00:49:15,1,1.40,1,N,114,79,1,10.0,1.00,0.5,3.15,0.0,1.0,18.90,2.5,0.0,0.75
2,1,2025-02-01 00:06:09,2025-02-01 00:11:51,0,0.40,1,N,211,144,1,6.5,4.25,0.5,1.00,0.0,1.0,13.25,2.5,0.0,0.75
3,1,2025-02-01 00:15:13,2025-02-01 00:20:19,0,0.70,1,N,113,249,1,7.2,4.25,0.5,2.00,0.0,1.0,14.95,2.5,0.0,0.75
4,2,2025-02-01 00:02:52,2025-02-01 00:20:25,1,4.19,1,N,113,263,1,19.8,1.00,0.5,5.11,0.0,1.0,30.66,2.5,0.0,0.75

In [5]:
df3 = spark.read.parquet(
    "hdfs://namenode:9000/project-data/yellow_tripdata3.parquet"
)

df3.limit(5).toPandas()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-03-01 00:17:16,2025-03-01 00:25:52,1,0.90,1,N,140,236,1,7.9,3.50,0.5,2.60,0.0,1.0,15.50,2.5,0.0,0.00
1,1,2025-03-01 00:37:38,2025-03-01 00:43:51,1,0.60,1,N,140,262,1,6.5,3.50,0.5,2.30,0.0,1.0,13.80,2.5,0.0,0.00
2,2,2025-03-01 00:24:35,2025-03-01 00:39:49,1,1.94,1,N,161,68,1,14.9,1.00,0.5,5.16,0.0,1.0,25.81,2.5,0.0,0.75
3,2,2025-03-01 00:56:16,2025-03-01 01:01:35,2,0.95,1,N,231,13,1,7.2,1.00,0.5,2.59,0.0,1.0,15.54,2.5,0.0,0.75
4,1,2025-03-01 00:01:44,2025-03-01 00:10:00,1,1.50,1,N,163,236,1,8.6,4.25,0.5,2.85,0.0,1.0,17.20,2.5,0.0,0.75

In [6]:
df = spark.read.parquet(
    "hdfs://namenode:9000/project-data/yellow_tripdata1.parquet",
    "hdfs://namenode:9000/project-data/yellow_tripdata2.parquet",
    "hdfs://namenode:9000/project-data/yellow_tripdata3.parquet"
    
)

In [7]:
df.printSchema()

root
 |-- VendorID: integer (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- tpep_dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: long (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- RatecodeID: long (nullable = true)
 |-- store_and_fwd_flag: string (nullable = true)
 |-- PULocationID: integer (nullable = true)
 |-- DOLocationID: integer (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- Airport_fee: double (nullable = true)
 |-- cbd_congestion_fee: double (nullable = true)

In [8]:
# data cleaning

In [9]:
print("Rows:", df.count())

Rows: 11198026

In [10]:
df = df.drop("store_and_fwd_flag")

In [11]:
from pyspark.sql.functions import col, count, when

nulls_df = df.select([
    count(when(col(c).isNull(), c)).alias(c)
    for c in df.columns
])

nulls_df.toPandas()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,0,0,0,2263749,0,2263749,0,0,0,0,0,0,0,0,0,0,2263749,2263749,0

In [12]:
df=df.dropna()

In [116]:
total_rows = df.count()
unique_rows = df.dropDuplicates().count()

print("Duplicates:", total_rows - unique_rows)

Duplicates: 0

In [13]:
from pyspark.sql.functions import when, col

df = df.withColumn(
    "payment_type_name",when(
     col("payment_type") == 1, "Credit Card")
    .when(col("payment_type") == 2, "Cash")
    .when(col("payment_type") == 3, "No Charge")
    .when(col("payment_type") == 4, "Dispute")
    .when(col("payment_type") == 5, "Unknown")
    .otherwise("Other")
)

In [14]:
ww=df.groupBy(
    "payment_type",
    "payment_type_name"
).count()
ww.toPandas()

   payment_type payment_type_name    count
0             1       Credit Card  7484734
1             5           Unknown        1
2             2              Cash  1135757
3             3         No Charge    72546
4             4           Dispute   241239

In [15]:
df.groupBy("RatecodeID").count().show()

+----------+-------+
|RatecodeID|  count|
+----------+-------+
|         6|     11|
|         5|  81032|
|         1|8391053|
|         3|  27178|
|         2| 288602|
|         4|  21318|
|        99| 125083|
+----------+-------+

In [16]:
from pyspark.sql.functions import when, col

df = df.withColumn(
    "Ratecode_name",
    when(col("RatecodeID") == 1, "Standard Rate")
    .when(col("RatecodeID") == 2, "JFK")
    .when(col("RatecodeID") == 3, "Newark")
    .when(col("RatecodeID") == 4, "Nassau/Westchester")
    .when(col("RatecodeID") == 5, "Negotiated Fare")
    .when(col("RatecodeID") == 6, "Group Ride")
    .when(col("RatecodeID") == 99, "Unknown")
    .otherwise("Other")
)

In [17]:
df.groupBy("Ratecode_name").count().show()

+------------------+-------+
|     Ratecode_name|  count|
+------------------+-------+
|     Standard Rate|8391053|
|        Group Ride|     11|
|           Unknown| 125083|
|            Newark|  27178|
|Nassau/Westchester|  21318|
|   Negotiated Fare|  81032|
|               JFK| 288602|
+------------------+-------+

In [18]:
df=df.filter(col("RatecodeID").isin([1,2,3,4,5,6]))

In [19]:
df = df.filter(col("payment_type").isin([1, 2]))

In [20]:
print("Invalid distance:",
      df.filter(col("trip_distance") <= 0).count())

Invalid distance: 78598

In [21]:
df = df.filter(col("trip_distance") > 0)

In [22]:
print("Invalid fare:",
      df.filter(col("fare_amount") <= 0).count())

Invalid fare: 42509

In [23]:
df = df.filter(col("fare_amount") > 0)

In [24]:
print("Invalid total:",
      df.filter(col("total_amount") <= 0).count())

Invalid total: 0

In [25]:
print("Invalid passengers:",
      df.filter(col("passenger_count") <= 0).count())

Invalid passengers: 64644

In [26]:
df = df.filter(col("passenger_count") > 0)

In [27]:
df.select(
    "trip_distance",
    "fare_amount",
    "total_amount"
).describe().show()

+-------+-----------------+------------------+------------------+
|summary|    trip_distance|       fare_amount|      total_amount|
+-------+-----------------+------------------+------------------+
|  count|          8309831|           8309831|           8309831|
|   mean|3.137174043611651|17.924587346000884|27.657052644019224|
| stddev|24.96412297927378|23.332960360070626| 26.92327752097895|
|    min|             0.01|              0.01|              1.01|
|    max|         69735.19|          46263.88|          46269.44|
+-------+-----------------+------------------+------------------+

In [28]:
df = df.filter(col("trip_distance") < 200)

In [29]:
df.select(
    "trip_distance",
    "fare_amount",
    "total_amount"
).describe().show()

+-------+-----------------+------------------+-----------------+
|summary|    trip_distance|       fare_amount|     total_amount|
+-------+-----------------+------------------+-----------------+
|  count|          8309800|           8309800|          8309800|
|   mean|3.124052771426442|17.917432639775424|27.64987048664263|
| stddev|4.217370955600751|16.863596164026387|21.55822490382487|
|    min|             0.01|              0.01|             1.01|
|    max|            196.3|            1421.2|          1438.01|
+-------+-----------------+------------------+-----------------+

In [30]:
df.filter(
    col("tpep_dropoff_datetime") <=
    col("tpep_pickup_datetime")
).count()

26599

In [31]:
df = df.filter(
    col("tpep_dropoff_datetime") >
    col("tpep_pickup_datetime")
)

In [32]:
df.filter(col("passenger_count") >= 7).count()

24

In [33]:
df = df.filter(col("passenger_count") < 7)

In [34]:
ww=df.select(
    "trip_distance",
    "fare_amount",
    "total_amount"
).describe()
ww.toPandas()

  summary      trip_distance        fare_amount        total_amount
0   count            8283177            8283177             8283177
1    mean  3.125794523043448  17.92477838998316  27.658298412541846
2  stddev  4.219122657767156   16.8734846214721  21.569898285958168
3     min               0.01               0.01                1.01
4     max              196.3             1421.2             1438.01

In [35]:
df.filter(col("PULocationID") <= 0).count()

0

In [36]:
df.filter(col("DOLocationID") <= 0).count()

0

In [37]:
from pyspark.sql.functions import unix_timestamp

df = df.withColumn(
    "trip_duration_minutes",
    (
        unix_timestamp("tpep_dropoff_datetime") -
        unix_timestamp("tpep_pickup_datetime")
    ) / 60
)

In [38]:
df.select("trip_duration_minutes").describe().show()

+-------+---------------------+
|summary|trip_duration_minutes|
+-------+---------------------+
|  count|              8283177|
|   mean|   15.155033797217497|
| stddev|    29.81698454487447|
|    min| 0.016666666666666666|
|    max|    8564.666666666666|
+-------+---------------------+

In [39]:
df.filter(
    (
        unix_timestamp("tpep_dropoff_datetime") -
        unix_timestamp("tpep_pickup_datetime")
    ) / 60 > 1000
).count()

2939

In [40]:
df = df.filter(
    (
        unix_timestamp("tpep_dropoff_datetime") -
        unix_timestamp("tpep_pickup_datetime")
    ) / 60 < 1000
)

In [41]:
df=df.drop("trip_duration_minutes")

In [42]:
df.count()

8280238

In [43]:
df.printSchema()

root
 |-- VendorID: integer (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- tpep_dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: long (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- RatecodeID: long (nullable = true)
 |-- PULocationID: integer (nullable = true)
 |-- DOLocationID: integer (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- Airport_fee: double (nullable = true)
 |-- cbd_congestion_fee: double (nullable = true)
 |-- payment_type_name: string (nullable = false)
 |-- Ratecode_name: string (nullable = false)

In [44]:
# insights

In [45]:
df.groupBy(
    "payment_type_name"
).count().orderBy("count", ascending=False).show()

+-----------------+-------+
|payment_type_name|  count|
+-----------------+-------+
|      Credit Card|7227074|
|             Cash|1053164|
+-----------------+-------+

In [46]:
from pyspark.sql.functions import avg

df.select(
    avg("total_amount").alias("avg_total")
).show()

+------------------+
|         avg_total|
+------------------+
|27.657356967263855|
+------------------+

In [47]:
from pyspark.sql.functions import avg

df.select(
    avg("trip_distance").alias("avg_total")
).show()

+-----------------+
|        avg_total|
+-----------------+
|3.125577381954416|
+-----------------+

In [48]:
df.groupBy(
    "passenger_count"
).count().show()

+---------------+-------+
|passenger_count|  count|
+---------------+-------+
|              6|  32436|
|              5|  52146|
|              1|6638300|
|              3| 253216|
|              2|1151908|
|              4| 152232|
+---------------+-------+

In [49]:
df.groupBy(
    "Ratecode_name"
).count().show()

+------------------+-------+
|     Ratecode_name|  count|
+------------------+-------+
|     Standard Rate|7935400|
|        Group Ride|      4|
|            Newark|  21919|
|Nassau/Westchester|  18612|
|   Negotiated Fare|  42867|
|               JFK| 261436|
+------------------+-------+

In [54]:
"""df.write.mode("overwrite").parquet(
    "hdfs://namenode:9000/big-data/cleaned_taxi"
)"""

'df.write.mode("overwrite").parquet(\n    "hdfs://namenode:9000/big-data/cleaned_taxi"\n)'

In [53]:
df.count()

8280238

In [50]:
# feature-engineer

In [5]:
df5 = spark.read.parquet("hdfs://namenode:9000/project-data//part-00000-58538248-1e4d-437a-8ecf-1e8ad91ba4f4-c000.snappy.parquet")

print(f"rows: {df5.count():,}")
print(f"columns: {len(df5.columns)}")
df5.printSchema()

rows: 8,280,238
columns: 25
root
 |-- VendorID: integer (nullable = true)
 |-- tpep_pickup_datetime: timestamp_ntz (nullable = true)
 |-- tpep_dropoff_datetime: timestamp_ntz (nullable = true)
 |-- passenger_count: long (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- RatecodeID: long (nullable = true)
 |-- PULocationID: integer (nullable = true)
 |-- DOLocationID: integer (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- extra: double (nullable = true)
 |-- mta_tax: double (nullable = true)
 |-- tip_amount: double (nullable = true)
 |-- tolls_amount: double (nullable = true)
 |-- improvement_surcharge: double (nullable = true)
 |-- total_amount: double (nullable = true)
 |-- congestion_surcharge: double (nullable = true)
 |-- Airport_fee: double (nullable = true)
 |-- cbd_congestion_fee: double (nullable = true)
 |-- payment_type_name: string (nullable = true)
 |-- Ratecode_name: string (nullable = true)
 |-- pickup_hour: integer (nullable = true)
 |-- dropoff_hour: integer (nullable = true)
 |-- trip_duration_minutes: double (nullable = true)
 |-- day_of_week: integer (nullable = true)

In [6]:
df5.limit(5).toPandas()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,...,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,payment_type_name,Ratecode_name,pickup_hour,dropoff_hour,trip_duration_minutes,day_of_week
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1,1.60,1,229,237,1,10.0,...,18.00,2.5,0.0,0.0,Credit Card,Standard Rate,0,0,8.35,4
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1,0.50,1,236,237,1,5.1,...,12.12,2.5,0.0,0.0,Credit Card,Standard Rate,0,0,2.55,4
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1,0.60,1,141,141,1,5.1,...,12.10,2.5,0.0,0.0,Credit Card,Standard Rate,0,0,1.95,4
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3,0.52,1,244,244,2,7.2,...,9.70,0.0,0.0,0.0,Cash,Standard Rate,0,0,5.57,4
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3,0.66,1,244,116,2,5.8,...,8.30,0.0,0.0,0.0,Cash,Standard Rate,0,0,3.53,4

In [7]:
from pyspark.sql.functions import hour

df5 = df5.withColumn("pickup_hour", hour("tpep_pickup_datetime"))
df5.select("tpep_pickup_datetime", "pickup_hour").show(5)

+--------------------+-----------+
|tpep_pickup_datetime|pickup_hour|
+--------------------+-----------+
| 2025-01-01 00:18:38|          0|
| 2025-01-01 00:32:40|          0|
| 2025-01-01 00:44:04|          0|
| 2025-01-01 00:14:27|          0|
| 2025-01-01 00:21:34|          0|
+--------------------+-----------+
only showing top 5 rows

In [8]:
df5.groupBy("pickup_hour")\
.count()\
.orderBy("pickup_hour")\
.show(24)

+-----------+------+
|pickup_hour| count|
+-----------+------+
|          0|208473|
|          1|137842|
|          2| 89159|
|          3| 59636|
|          4| 37725|
|          5| 41019|
|          6| 95730|
|          7|208764|
|          8|301993|
|          9|352742|
|         10|383647|
|         11|413634|
|         12|449657|
|         13|473758|
|         14|509769|
|         15|534775|
|         16|546147|
|         17|598014|
|         18|609941|
|         19|527109|
|         20|487898|
|         21|492356|
|         22|420282|
|         23|300168|
+-----------+------+

In [9]:
df5 = df5.withColumn("dropoff_hour", hour("tpep_dropoff_datetime"))
df5.select("tpep_dropoff_datetime", "dropoff_hour").show(5)

+---------------------+------------+
|tpep_dropoff_datetime|dropoff_hour|
+---------------------+------------+
|  2025-01-01 00:26:59|           0|
|  2025-01-01 00:35:13|           0|
|  2025-01-01 00:46:01|           0|
|  2025-01-01 00:20:01|           0|
|  2025-01-01 00:25:06|           0|
+---------------------+------------+
only showing top 5 rows

In [10]:
df5.groupBy("dropoff_hour")\
.count()\
.orderBy("dropoff_hour")\
.show(24)

+------------+------+
|dropoff_hour| count|
+------------+------+
|           0|231245|
|           1|152883|
|           2| 98656|
|           3| 63786|
|           4| 41630|
|           5| 36732|
|           6| 80335|
|           7|178079|
|           8|282862|
|           9|342012|
|          10|376356|
|          11|402435|
|          12|443477|
|          13|463260|
|          14|489427|
|          15|528899|
|          16|540349|
|          17|592384|
|          18|629980|
|          19|552684|
|          20|492217|
|          21|488656|
|          22|444391|
|          23|327503|
+------------+------+

In [11]:
from pyspark.sql.functions import unix_timestamp, round as spark_round

df5 = df5.withColumn(
    "trip_duration_minutes",
    spark_round(
        (unix_timestamp("tpep_dropoff_datetime") - 
         unix_timestamp("tpep_pickup_datetime")) / 60.0, 
        2
    )
)
df5.select(
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
    "trip_duration_minutes"
).show(5)

+--------------------+---------------------+---------------------+
|tpep_pickup_datetime|tpep_dropoff_datetime|trip_duration_minutes|
+--------------------+---------------------+---------------------+
| 2025-01-01 00:18:38|  2025-01-01 00:26:59|                 8.35|
| 2025-01-01 00:32:40|  2025-01-01 00:35:13|                 2.55|
| 2025-01-01 00:44:04|  2025-01-01 00:46:01|                 1.95|
| 2025-01-01 00:14:27|  2025-01-01 00:20:01|                 5.57|
| 2025-01-01 00:21:34|  2025-01-01 00:25:06|                 3.53|
+--------------------+---------------------+---------------------+
only showing top 5 rows

In [12]:
from pyspark.sql.functions import dayofweek

df5 = df5.withColumn("day_of_week", dayofweek("tpep_pickup_datetime"))
df5.select("tpep_pickup_datetime", "day_of_week").show(5)

+--------------------+-----------+
|tpep_pickup_datetime|day_of_week|
+--------------------+-----------+
| 2025-01-01 00:18:38|          4|
| 2025-01-01 00:32:40|          4|
| 2025-01-01 00:44:04|          4|
| 2025-01-01 00:14:27|          4|
| 2025-01-01 00:21:34|          4|
+--------------------+-----------+
only showing top 5 rows

In [13]:
df5.groupBy("day_of_week")\
.count()\
.orderBy("day_of_week")\
.show(7)

+-----------+-------+
|day_of_week|  count|
+-----------+-------+
|          1|1017603|
|          2|1017385|
|          3|1111365|
|          4|1250785|
|          5|1329510|
|          6|1264592|
|          7|1288998|
+-----------+-------+

In [14]:
from pyspark.sql.functions import col

selected_columns = [
    "VendorID",
    "passenger_count",
    "trip_distance",
    "pickup_hour",
    "day_of_week",
    "trip_duration_minutes",
    "RatecodeID",
    "payment_type",
    "fare_amount",
    "PULocationID",
    "DOLocationID",
    "payment_type_name",
    "Ratecode_name",
    "total_amount"
]
df_engineered = df5.select([col(c) for c in selected_columns])
print(f"final_shape: {df_engineered.count():,} rows x {len(df_engineered.columns)} columns")
df_engineered.printSchema()

final_shape: 8,280,238 rows x 14 columns
root
 |-- VendorID: integer (nullable = true)
 |-- passenger_count: long (nullable = true)
 |-- trip_distance: double (nullable = true)
 |-- pickup_hour: integer (nullable = true)
 |-- day_of_week: integer (nullable = true)
 |-- trip_duration_minutes: double (nullable = true)
 |-- RatecodeID: long (nullable = true)
 |-- payment_type: long (nullable = true)
 |-- fare_amount: double (nullable = true)
 |-- PULocationID: integer (nullable = true)
 |-- DOLocationID: integer (nullable = true)
 |-- payment_type_name: string (nullable = true)
 |-- Ratecode_name: string (nullable = true)
 |-- total_amount: double (nullable = true)

In [15]:
rr=df_engineered.describe()
rr.toPandas()

,summary,VendorID,passenger_count,trip_distance,pickup_hour,day_of_week,trip_duration_minutes,RatecodeID,payment_type,fare_amount,PULocationID,DOLocationID,payment_type_name,Ratecode_name,total_amount
0,count,8280238,8280238,8280238,8280238,8280238,8280238,8280238,8280238,8280238,8280238,8280238,8280238,8280238,8280238
1,mean,1.7874232600560516,1.3002087621152918,3.1255773819544883,14.45889465979118,4.184384072052035,14.65396771928529,1.0643215810946498,1.1271900638604833,17.9236292773135,166.97908067376807,166.21793371156724,None,None,27.65735696729847
2,stddev,0.40913065125226783,0.7317596877427782,4.2187237544522,5.62167040318989,1.9672980892614345,12.63493367904239,0.3756316763619525,0.3331857813932029,16.87109779277475,62.736286457842965,68.65374460643555,None,None,21.567804917033975
3,min,1,1,0.01,0,1,0.02,1,1,0.01,1,1,Cash,Group Ride,1.01
4,max,2,6,196.3,23,7,995.0,6,2,1421.2,265,265,Credit Card,Standard Rate,1438.01

In [16]:
df_engineered.coalesce(1).write.mode("overwrite").parquet(
    "hdfs://namenode:9000/big-data/cleaned_taxi_enigneered"
)